# Permanent redirect from Netlify subdomain to custom domain
[[redirects]]
  from = "https://simpleimagecompressor.netlify.app/*"
  to = "https://simplecompress.com/:splat"
  status = 301
  force = true
