# Redirect rule for netlify subdomain to custom domain

[[redirects]]
  from = "/*"
  to = "https://simplecompress.com/:splat"
  status = 301
  force = true
  [redirects.conditions]
    host = "simpleimagecompressor.netlify.app"
